# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'

target 'client' do
pod 'Alamofire'
pod 'ObjectMapper'
pod 'Bolts'
pod 'Kingfisher'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Typhoon'
pod 'Cloudinary'
pod 'Bond'
pod 'IDMPhotoBrowser', '1.8.1'
pod 'Google/SignIn'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'NVActivityIndicatorView'
pod 'SDWebImage'

use_frameworks!
end

target 'clientTests' do

end

target 'clientUITests' do

end

