# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'client' do
pod 'Alamofire'
pod 'ObjectMapper'
pod 'Bolts'
pod 'Kingfisher'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Typhoon'
pod 'Cloudinary'
pod 'Bond'
pod 'IDMPhotoBrowser'
pod 'NVActivityIndicatorView'

use_frameworks!
end

target 'clientTests' do

end

target 'clientUITests' do

end

