# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'client' do
pod 'Alamofire'
pod 'ObjectMapper'
pod 'SDWebImage', '~> 3.7'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Typhoon'
pod 'Cloudinary'
use_frameworks!
end

target 'clientTests' do

end

target 'clientUITests' do

end

